// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqbmnasrpmtbzraxgatu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xYm1uYXNycG10YnpyYXhnYXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mzk3NjUsImV4cCI6MjA2NTUxNTc2NX0.Mruzk9F-rwa4mXV7ETGbCsGEJoiMo0etl8Fk5WZfL8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);